build_from:
  armv7: homeassistant/armv7-base-ubuntu:20.04
  aarch64: homeassistant/aarch64-base-ubuntu:20.04
  amd64: homeassistant/amd64-base-ubuntu:20.04
labels:
  org.opencontainers.image.title: "Home Assistant Homegear Add-on"
  org.opencontainers.image.description: "Add-on providing support for Homegear, esp. CUL stick"
  org.opencontainers.image.source: "https://github.com/sarmbruster/home-assistant-addons/homegear"
  org.opencontainers.image.licenses: "Apache License 2.0"
  org.opencontainers.image.authors: "stefan@armbruster-it.de"
args:
  TEMPIO_VERSION: "2021.09.0"
# args:
#   my_build_arg: xy
#   HOMGEAR_VERSION: "nightly"
