name: Homegear
version: 0.0.22
slug: homegear
description: Homegear as a Hassio add-on
arch:
- armv7
- armhf
- amd64
init: false
startup: services
boot: auto
webui: http://[HOST]:[PORT:2001]
# privileged:
# - SYS_ADMIN
# - SYS_RAWIO
usb: true
map:
- config:rw
- share:rw
ports:
  '2001': 2001
  '2002': 2002
  '2003': 2003
options:
  device:
  centralAddress: "0x112233"
  rfKey: 00112233445566778899AABBCCDDEEFF
schema:
  device: "device(subsystem=tty)"
  centralAddress: str
  rfKey: str
